-- ============================================================================
-- APIP Trading Intelligence & Performance Platform
-- Phase 1.6 -- post_trade_reviews
-- ============================================================================
-- Confirmed against live schema (information_schema.columns query) before
-- writing: this table does not exist yet. Shaped to match ReviewService's
-- PostTradeReview output type in coachingService.ts exactly.
--
-- Per notebook cell 0 core rule: "Historical backfill rows cannot be used
-- for coaching-alignment reviews." The service enforces this by contract
-- (caller must filter before passing trades). This table should therefore
-- never contain rows linked to historical_backfill === true trades --
-- not enforced by a DB constraint here (no FK to actual_trades.historical_
-- backfill), but documented as a caller responsibility.
-- ============================================================================

create table post_trade_reviews (
  review_id                  uuid primary key default gen_random_uuid(),
  trade_id                   uuid not null references actual_trades(trade_id),
  recommendation_version_id  uuid references recommendation_versions(recommendation_version_id),
  market                     text not null,
  session                    text not null,
  direction_alignment        text not null check (direction_alignment in ('Aligned', 'Different')),
  entry_alignment            text not null check (entry_alignment in ('High', 'Low')),
  alignment_score            integer not null check (alignment_score between 0 and 2),
  analyst_facing_review      text not null,
  created_at                 timestamptz not null default now()
);

comment on table post_trade_reviews is
  'Post-trade coaching-alignment reviews, generated by ReviewService (coachingService.ts buildPostTradeReviews()). Per notebook cell 0: historical backfill rows are excluded by the caller before passing trades to this service -- see ReviewService contract note.';

comment on column post_trade_reviews.alignment_score is
  'Sum of direction_alignment (1 if Aligned) + entry_alignment (1 if High). Range 0-2. Per notebook build_post_trade_reviews() alignment_score formula.';
