-- ============================================================================
-- APIP Trading Intelligence & Performance Platform
-- Migration 047 -- post_trade_reviews schema drift correction
-- ============================================================================
-- Reconciles the live schema against 033_post_trade_reviews.sql.
-- Three changes were made out-of-band (via Supabase Studio or applied scripts)
-- between migration 033 and now -- confirmed live via PostgREST introspection
-- before writing this migration: stop_alignment, target_alignment and
-- review_status all already exist on the live table (033/034 already track
-- review_status's own addition; stop_alignment/target_alignment were not
-- tracked anywhere). alignment_score's column comment is still the original
-- "Range 0-2" text live, confirming it was never updated for the 0-4 scoring
-- generatePostTradeReviews.ts has been writing (confirmed live: alignment_score
-- values up to 4 already exist on this table, which a still-enforced 0-2 check
-- constraint would reject) -- this migration corrects the comment either way,
-- and the constraint rewrite converges it to 0-4 whether it was still 0-2,
-- already manually widened, or unconstrained.
--   1. alignment_score constraint was 0-2 (direction + entry only).
--      Extended to 0-4 when stop_alignment and target_alignment were added
--      (each contributing 1 point). Corrected here.
--   2. stop_alignment column added (nullable text, 'High' or 'Low').
--   3. target_alignment column added (nullable text, 'High' or 'Low').
--   4. review_status column added with default 'PENDING'.
-- RLS policies for this table are in 035_post_trade_reviews_rls.sql.
-- ============================================================================

-- 1. Fix alignment_score constraint (0-2 → 0-4)
alter table post_trade_reviews
  drop constraint if exists post_trade_reviews_alignment_score_check;

alter table post_trade_reviews
  add constraint post_trade_reviews_alignment_score_check
  check (alignment_score between 0 and 4);

-- 2. Add stop_alignment
alter table post_trade_reviews
  add column if not exists stop_alignment text
  check (stop_alignment in ('High', 'Low', 'Unknown'));

-- 3. Add target_alignment
alter table post_trade_reviews
  add column if not exists target_alignment text
  check (target_alignment in ('High', 'Low', 'Unknown'));

-- 4. Add review_status
alter table post_trade_reviews
  add column if not exists review_status text not null default 'PENDING'
  check (review_status in ('PENDING', 'GENERATED', 'ACKNOWLEDGED', 'MANAGER_REVIEWED', 'CLOSED'));

-- Update comment to reflect 0-4 scoring
comment on column post_trade_reviews.alignment_score is
  'Sum of direction (1) + entry (1) + stop (1) + target (1) alignment scores. Range 0-4.';

comment on column post_trade_reviews.stop_alignment is
  'Stop placement alignment: High if within suggested risk range (±0.5 ATR20), Low otherwise.';

comment on column post_trade_reviews.target_alignment is
  'Target placement alignment: High if within suggested target range (±0.5 ATR20), Low otherwise.';

comment on column post_trade_reviews.review_status is
  'Lifecycle status of this review. GENERATED by engine, ACKNOWLEDGED by analyst, MANAGER_REVIEWED/CLOSED by manager.';
