-- ============================================================================
-- Migration 058 — RLS policies for analyst_availability (documentation only)
-- ============================================================================
-- These policies already existed in the live database but were undocumented
-- in the migration history. Confirmed live on 2026-08-20:
--   analyst_availability_select_own   (SELECT) — own rows or MANAGER/ADMIN
--   analyst_availability_insert_own   (INSERT) — own rows or MANAGER/ADMIN
--   analyst_availability_update_manager (UPDATE) — MANAGER/ADMIN only
--   analyst_availability_delete_own   (DELETE) — own PENDING rows only
-- The enable row level security call below is idempotent.
-- ============================================================================
alter table analyst_availability enable row level security;
